### ISSUE TITLE
No Event Loop and No Consoles to Debug

### ISSUE THREAD

**Issue by SpencerGresoro** [bakermd86/FoogleBrowser#3] opened 2023-04-14 16:13 UTC
![image](https://user-images.githubusercontent.com/18724865/232097712-8ee3a6b1-67a3-4ea9-8322-749a0a4e5166.png)
![image](https://user-images.githubusercontent.com/18724865/232098930-46cca672-9fe8-4570-a91b-505c665cc195.png)

Client starts:

Window that triggers event loop is visible - but not moving to initialize the drag - 

AD&D 2e and DND 5e -- both tested.

New Campaign - no extensions - both rulesets tested

Same result.

Manual dragging will start to initialize indexing - 
(first image I did this - hence the offset of the pane)

Release === stop 

There is no consoles in this last version you sent.

**Comment by SpencerGresoro** [comment] 2023-04-14 16:47
Switching speeds, rebuild index and setting modules to index, all appear to have no effect IF you started with a speed set.

In order for me to get indexing to work, you must set blocking and reboot the client. 

To me it feels like no initial event is being called AND that no event is attached to rebuild, or its being whacked, on client init.  

Thank you sirnoob

**Comment by SpencerGresoro** [comment] 2023-04-14 17:02
![image](https://user-images.githubusercontent.com/18724865/232109451-f6635c21-429b-4503-a435-02cc6387c691.png)

I  wanted to see what would happen if I dragged it too completion - 
The above was the result..

Afterwards I hit rebuild index -- it move about 5px and stopped - most likely this is just initial positioning.

PS. I'll be around - don't know why we were not using git for issues to begin with - much better 👍

**Comment by bakermd86** [comment] 2023-04-15 08:39
It looks like there is a potential race condition that can develop between the size and position event handlers. I can't reproduce it without doing weird things like adding os.clock() loops into the handlers, but it causes the handlers to eventually re-use a size/position in 2 consecutive events, which causes the next onMove or onSizeChange not to fire.

I tweaked the event trigger to use random size/location values and check to make sure that they don't match the current window size/position before setting them, hopefully that will ensure that the event loop doesn't die prematurely. 

The little bit of movement you see at the beginning is probably the event loop running a few times and then exiting prematurely when the size/position events are handled out-of-order. 

The newest ext might help with that (instead of seeing the window slowly wiggle around the screen, it should randomly flash around all over the place like crazy):

https://github.com/bakermd86/FoogleBrowser/raw/AsyncTest3/FGBrowser.ext

If it doesn't work, I have a bunch of debug prints in the console log so provide that file. You won't see the console pop up, just go to %appdata%\SmiteWorks\Fantasy Grounds and grab the console.log file. That is where the debug prints I mentioned previously are going,

**Comment by bakermd86** [comment] 2023-04-15 09:15
I found another issue which I fixed to make the behavior more reliable in this new mode (the above link has that change). Basically: part of what was allowing the issue to happen was that the getSize() call on the window doesn't work as documented unless the window has the "dynamic" tag in the sizelimits. 

I am pretty sure that using random size/location and safety checking against getSize() now should ensure that the events don't die off. I also pinned the range of size/location for the window to keep it up in the top left of the screen near the character portraits.

If this newest version works for you, I can take the frame back off that window and it should be good-to-go.

**Comment by SpencerGresoro** [comment] 2023-04-15 16:53
Race conditions ugh -- do they have promises in Lua ? probably not. You fixed the problem, however I'd like to keep using this build (and any other future build) live for awhile to ensure stability.  This is great work, as per usual. I'll create a new issue if I notice anything

**Comment by SpencerGresoro** [comment] 2023-04-15 17:54
2 out of 5 tests - It got about 90% done - then froze on sizing the frame. I grabbed it and resized a bit, and it kicked it back on. Interesting... 
I'm going to hammer on it all day - I thought perhaps that the client losing focus (because I had minified the main window), might have had something to do with it. Or maybe clicking around? But that doesn't seem to be the case. It works great, most of the time. Definitely feels like a timing/race issue. I prefer the blocking mode, particularly if it blocked and ran indexing only when I told it too prepare itself (like a full manual mode). I've been running the console/debug on to see what happens. When it froze those two times, it froze on SIZING.

**Comment by bakermd86** [comment] 2023-04-16 09:02
Yeah the size has been the issue I have always run into, the getSize() callback is just not reliable enough to avoid the scenario where the size is set the same. The problem was that anytime setSize() is called with a size that matches the window's current size, it doesn't trigger the onSizeChanged callback. I had various tricks to try to avoid that, but they were not perfect.

I realized something looking into it today that actually allowed me to have a much more elegant solution to maintaining the event loop. One which should be immune to that entire type of issue. Specifically: I found that the way sizelimit minimums work on windows is that they allow you to resize a window to any size, but if a window is sized below the minimum size, it will then resize it back to the minimum.

So I realized I can just simplify everything way down, get rid of the position handler altogether, and just have an onSizeChanged handler that sets the window size to a static value below the minimum sizelimit everytime. That way, it won't overflow the stack because when it calls setSize(x,y) and triggers the handler, the second setSize(x,y) call will be ignored because it matches the current window size. But then the UI will resize the window to the minium, which is > x,y, and will trigger another size change, which then sets the size back to x,y.

It should avoid the potential for the entire class of issues where the size handling resets the size to a matching size, and breaks the loop. Because the client itself is firing the subsequent minimum size resize events, and since the size is just static, they will never match.

This build has the changes:

https://github.com/bakermd86/FoogleBrowser/raw/master/FGBrowser.ext

There's also a bunch of printstack() debug prints, so if it does have an issue provide the console.log file from it so I can see the output when it stops. I don't think it CAN stop running with this change though, I made the change this morning before my kids got up and made a test extension that just opens a window doing this setSize() trick. I left that running for 5 hours and it never stopped. A window running the old method stopped after 20 minutes or so.

**Comment by SpencerGresoro** [comment] 2023-04-16 16:28
Very good find, Its tricky to debug this with only console logs. Do you have to reload every change you make to code? or can you live edit the lua file, and keep spamming rebuild? 

We are so spoiled with modern IDEs this just feel painful to me. Im wondering what the options/tools are for writing these..?

I've got a game I'm running today but I'm going to be use the blocking variant of this. I honestly prefer just buffing everything at once and waiting (in fact i'd love to see a manual mode, a button baked right into the browser model (bottom) to rebuild/build index) - Reasons- for those who don't have super rigs they can load FG fast, and do the indexing when they want and are prepared to wait. Aka blocking but full manual init. The trouble i have with async indexing is that even though it's running in the background and not blocking the ui, its still so slow and unresponsive that i might as well just wait.

However, for those with excellent specs, mileage of course will vary widely.

Just a thought - a full manual blocking would solve the slow load and leave the problem in the users hands on when/where to index:)

I will however, continue to hammer and test this async version.

**Comment by bakermd86** [comment] 2023-04-16 19:06
I didn't realize that you were still having slowness on the more recent versions, I was just looking at keeping the async events propagating. I guess I didn't realize how big the difference can be between different environments. Is your %appdata% directory on a platter HDD? That is the only metric I could see making that big of a difference in the per-node indexing (since the data has to be read from disk). 

For example, when I run indexing I don't see any effect of settings 1-3, and I can occasionally notice a little hiccup on 4, and 5 is noticeably slow. But changing the weights of the event loop is pretty easy, I am curious if running fractional weights would help in this case.

Just to test, I changed the slower weights to be fractional in this version:

https://github.com/bakermd86/FoogleBrowser/raw/SlowMode/FGBrowser.ext

The old weights were 1, 2, 4, 8, 16 meaning that for each eventLoop call, that is how many records would be iterated over on each call. I changed the weights for this test to 1/8, 1/4, 1, 4, 8. So on setting 1, it only processes 1 record for every 8 calls to the event loop. I am just curious if that even has an effect. Even on my laptop with a much slower SSD, I don't get any noticeable performance impact (but I don't have any platter drives to test those). 

I also added an Index on Load option to make the indexing manual if desired. 

Thanks for all your help testing this, I don't really have any older/slower HW to test with, so things that perform well for me are obviously too aggressive for real-world applications.

**Comment by bakermd86** [comment] 2023-04-16 19:14
> Very good find, Its tricky to debug this with only console logs. Do you have to reload every change you make to code? or can you live edit the lua file, and keep spamming rebuild?

On this topic: yeah I just have a little bash script that I keep in my project directory, and then set that script as a run configuration in my IDE. That way I can just hit the button as if I were running a project from the IDE, and it gets installed to FG. Then I just have a hotkey in the client to /reload. So it is 2 button clicks and then 20(ish) seconds to reload the campaign. It is more annoying than just running something in a debugger, but not nearly as annoying as the stuff I support at work...

**Comment by SpencerGresoro** [comment] 2023-04-16 20:07
> > Very good find, Its tricky to debug this with only console logs. Do you have to reload every change you make to code? or can you live edit the lua file, and keep spamming rebuild?
> 
> On this topic: yeah I just have a little bash script that I keep in my project directory, and then set that script as a run configuration in my IDE. That way I can just hit the button as if I were running a project from the IDE, and it gets installed to FG. Then I just have a hotkey in the client to /reload. So it is 2 button clicks and then 20(ish) seconds to reload the campaign. It is more annoying than just running something in a debugger, but not nearly as annoying as the stuff I support at work...

Id like to try my hand at writing/modifying extensions myself. I’ve been working on the same tech for so long I’d like to try something new. This is gonna be super green, but can you actual set break points in vscode when you fire the run command and have it hit your break to examine the stack trace/ ect.? Using a bash was clever, I bet a lot of people run it full manual — headache.


With regards to slowness, i should have been more detailed- it’s not bad at all - i have fast ssd and last gen i7 - RAM 16 gb on my box and 12 on laptop. Im actually going to build a new box this week because I can’t have win11 on this board. It’s time, been 5 or 6 years. I just personally prefer to index when i’m ready so i can start up fast and do a few things and then prep it when i need it. I was running on 4 and it hangs abit , it’s working hard to get its job done :)

Later tonight i’ll test the hell out of everything- im actually running an ADND 2e game today.

Once again i have to say this is one, if not the most amazing extensions for FG. You wrote one of the best workflow tools for DMS and players alike - i honestly think you should speak to moon wizard or another dev at smiteworks - they’ll be able to help you optimize since they can see what’s under the hood. Id at least reach and explain your implementation. This should br apart of Core Rpg… I saw him hop in the thread 🧵 

I might have some serious beginner questions for you about setting up an environment to write an extension or collab. Did you read a basic dev doc for smiteworks - i know they have one.

**Comment by SpencerGresoro** [comment] 2023-04-16 20:12
Ps. was reading through the scripts, the indexer is impressive work for someone who doesn’t know lua well :)

The shitty thing is you’re limited to the lua libraries and core that the client has… else you could use async/await libraries. Do you know what version of lua/live they’re using? In other words how are your researching things and find what you have:don’t have in your arsenal

**Comment by SpencerGresoro** [comment] 2023-04-16 20:12
phone typing- forgive

**Comment by SpencerGresoro** [comment] 2023-04-16 20:14
i work primarily in visual studio and chrome dev tools 99% of the time. MVC C#, angular, heavy complex js, all web techs. Phone typing so forgive

**Comment by bakermd86** [comment] 2023-04-17 18:42
> Ps. was reading through the scripts, the indexer is impressive work for someone who doesn’t know lua well :)
> 
> The shitty thing is you’re limited to the lua libraries and core that the client has… else you could use async/await libraries. Do you know what version of lua/live they’re using? In other words how are your researching things and find what you have:don’t have in your arsenal

Yeah, no async/await/futures/threads/executors/semaphores/anything. And all the code is strictly synchronous with the client itself. From Debug.printstack() output it looks to me like the calls to the lua interpreter are coming from the main application event thread. So anytime Lua code is executing it just blocks the entire UI. 

As for my preferred IDEs, I like Jetbrains IDEs because I prefer their search interface to VS or VSCode. I support backend infrastructure stuff, so it is 50% Java, 40% C/C++ and 10% python. That's why waiting 20-30 seconds to reload an extension doesn't bother me, I'm used to waiting 20-30 minutes for a build script so I can then wait another 20 minutes for a startup sequence.

> I might have some serious beginner questions for you about setting up an environment to write an extension or collab. Did you read a basic dev doc for smiteworks - i know they have one.

I use the ruleset API reference:

https://fantasygroundsunity.atlassian.net/wiki/spaces/FGCP/pages/996644535/Developer+Guide+-+Ruleset+API+Reference

It says in the page that it is a WIP and to use the refdoc, but my experience is that this is more complete than the refdoc. The other thing I do is just take the CoreRPG.pak file out and unzip it, then search it from my IDE. There are lots of classes/templates/functionality in CoreRPG that are not documented anywhere, but I have found it is generally pretty easy to find that with the search functionality in the IDE and do my own implementation.

I started playing around with FG dev because my group wanted to run the Modiphius 2d20 Star Trek setting and there was (at that time) no official ruleset for it, so I just figured I'd have a go at it. That is why that ruleset (https://forge.fantasygrounds.com/shop/items/486/view) has lots of unusual features like recolorable windows, and various automated wizards. I wanted to use it as a learning project.

**Comment by SpencerGresoro** [comment] 2023-04-17 19:56
Appreciate the information! As for the 2d20 Star Trek - that's a cool project to cut your teeth on. Question, which branch do you want me to test? I see you have a slow mode now.

**Comment by bakermd86** [comment] 2023-04-18 01:52
Slow Mode is the build with the test to see if adding fractional async weights improve the UI responsiveness in your environment. So in that branch, using level 1 or 2 for the indexing priority will do 1/4 or 1/8 of the indexing rate. I am just curious whether kicking control back to the UI more frequently improves the usability, or if the issue is just that the records are slow to index in general and kicking back to the UI more often does nothing.

**Comment by bakermd86** [comment] 2023-04-18 19:42
I was working on another project for my houserules extension, and I ended up doing something there that gave me an idea for an entirely different way to break up the indexing work in order to do only a single disk operation at a time between returning to the UI loop. 

The main change is that this version doesn't index per-node, it breaks up the node into its children and indexes each child separately, returning to the main UI loop between each 1-512 children (depending on weight). It works much better on my PC, even up to 512x I don't see any significant slowdown, so there should be a value that works for any system.

https://github.com/bakermd86/FoogleBrowser/raw/master/FGBrowser.ext

**Comment by SpencerGresoro** [comment] 2023-04-19 22:15
Im absolutely going to do some testing on everything real soon. Im actually right in the middle of a release (friday) - so i've been very busy. By the way I used the last version during my game on Sunday- it worked great. Only thing i noticed was that the players were having to wait abit until their characters were selectable. I honestly don't know how this would be related, since i was using blocking on my end.. and they joined well after i had the server up. Just might be something to keep an eye on. 

Scoot was telling me for him it was bad, like a min to propagate. I don't think it was nearly as bad on my game. And furthermore, i've had this happen in other peoples games. 

I'll report back!

**Comment by bakermd86** [comment] 2023-04-20 03:40
Regarding the player experience: I don't know why it would impact the character selection opening, but each client does build is own index. So you may have had blocking enabled, but the players have their own search settings and the default is non-blocking. I considered having the index built on the host and then doing search via OOB messaging, but I figured the actual impact of just indexing per-client is not going to be too much.

It also helps make sure that the clients can only search records they actually have permissions to view.  

If the indexing is preventing character selection though, I can just move the indexing trigger from onDesktopInit to onIdentityActivation for clients. That way, they can get in, select their character, and then the indexing can happen after they are in.

**Comment by bakermd86** [comment] 2023-04-20 11:28
I took a look at the character selection thing, it seems that the client fires off dozens of DB update events for the charsheets when loading the character list, and indexing each one slows down the population of the character list. I made some changes to avoid that.

I also added an "automatic" option for the indexing weight that adjusts the loop count continuously to try to maintain a responsive UI regardless of how much time each individual element takes.

**Comment by SpencerGresoro** [comment] 2023-04-20 21:14
That is excellent! What branch should I be testing off of ?

**Comment by SpencerGresoro** [comment] 2023-04-20 21:59
Version on HEAD is excellent. The ability to run index manually after run, and skip autoload is great. And I'd swear its x2/x3 times faster doing it after FG loads up. For me, with auto index on, it was at least a minute/2 to load. I just now did a advanced index (Basic off) - manually, after load, and it was done in 30 seconds. This is really working nice. 

I'll keep hammering at it - I tried the version on the re-entrancetest branch and it took forever to load. Let me know if you have anything you'd like me to check.

**Comment by bakermd86** [comment] 2023-04-21 03:39
Yeah head is the version to be on, I thought I had deleted that test branch. I merged it a while back and that is the same fundamental architecture as it has now, just with some other tweaks for performance.

Thanks for all the testing, I'm going to push this version to the forge. I think the option to configure the indexing behavior should ensure it works in pretty much any environment.

**Closed as completed** 2023-04-23 04:23 UTC
